maxAge: "24h"
maxItems: 10
outputDir: "static/index.html"
templatePath: "internal/templates/index.html"
timezone: "Europe/Madrid"
feeds:
  - name: "Ara.cat"
    url: "https://www.ara.cat/rss/latest"
    time_format: "Mon, 02 Jan 2006 15:04:05 -0700"
    order: 1
  - name: "El País"
    url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"
    time_format: "Mon, 02 Jan 2006 15:04:05 MST"
    order: 2
  - name: "Reuters"
    url: "https://rss-bridge.ggc-project.de/?action=display&bridge=ReutersBridge&feed=home%2Ftopnews&format=Mrss"
    time_format: "Mon, 02 Jan 2006 15:04:05 -0700"
    order: 3
